DirectionNorth: kd:w
DirectionNorthwest: kd:q
DirectionNortheast: kd:e
DirectionWest: kd:a
DirectionEast: kd:d
DirectionSouth: kd:x
DirectionSouthwest: kd:z
DirectionSoutheast: kd:c
Inventory: i
Quit: escape
